---
- name: Setup | copy init file
  ansible.builtin.copy:
    dest: "{{ item.dest }}"
    src: "{{ ansible_os_family | lower }}{{ item.dest }}"
    owner: "root"
    group: "root"
    mode: "0755"
  loop: "{{ os_service_init }}"
  become: true

- name: Setup | template configuration
  ansible.builtin.template:
    dest: "{{ item.dest }}"
    src: "{{ ansible_os_family | lower }}{{ item.dest + '.j2' }}"
    owner: "root"
    group: "{{ os_service_name }}"
    mode: "0640"
    backup: false
  loop: "{{ os_service_conf }}"
  become: true
  changed_when: true
  notify:
    - systemctl restart service

- name: Setup | flush handlers
  ansible.builtin.meta: flush_handlers

- name: Setup | start haproxy service
  ansible.builtin.service:
    name: "haproxy.service"
    state: "started"
  become: true
  when: ansible_distribution == "Ubuntu"

- name: Setup | create db tables
  ansible.builtin.shell: su -s /bin/sh  -c "placement-manage db sync" placement
  become: true
  delegate_to: "{{ groups['placement'][0] }}"
  run_once: true
...
