---
- name: systemctl restart service
  service:
    name: "{{ os_systemd_service_name }}.service"
    state: "restarted"
    enabled: true
  become: true
  changed_when: false
  register: restart_systemd_service
  failed_when: restart_systemd_service.failed
...
